include:
  - local: "CI/template.yml"

DeepSet:baseline_4param:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: baselineTRK_4param_021024
    Dataset: All200_part0.root
    SCRAM_ARCH: 'el9_amd64_gcc12'
    CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3'

# DeepSet:baseline_5param:
#   extends: .ml_pipeline
#   variables:
#     Model: DeepSet
#     Classes: btgc
#     Inputs: baseline
#     DataDir: baselineTRK_5param_021024
#     Dataset: All200_part0.root
#     SCRAM_ARCH: 'el9_amd64_gcc12'
#     CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
#     CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3'

# DeepSet:baseline_4param_extended_trk:
#   extends: .ml_pipeline
#   variables:
#     Model: DeepSet
#     Classes: btgc
#     Inputs: baseline
#     DataDir: extendedTRK_4param_021024
#     Dataset: All200_part0.root
#     SCRAM_ARCH: 'el9_amd64_gcc12'
#     CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
#     CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3'

# DeepSet:baseline_5param_extended_trk:
#   extends: .ml_pipeline
#   variables:
#     Model: DeepSet
#     Classes: btgc
#     Inputs: baseline
#     DataDir: extendedTRK_5param_021024
#     Dataset: All200_part0.root
#     SCRAM_ARCH: 'el9_amd64_gcc12'
#     CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
#     CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3'
