include:
  - local: "CI/template.yml"

# DeepSet:baseline_4param:
#   extends: .ml_pipeline
#   variables:
#     Name: baseline_4param
#     Inputs: baseline
#     DataDir: baselineTRK_4param_221124
#     Dataset: All200.root
#     MINBIAS: MinBias_PU200.root
#     BBBB: ggHHbbbb_PU200.root
#     EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_ntuples_v131Xv9
#     SCRAM_ARCH: 'el9_amd64_gcc12'
#     CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
#     CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3-JetTaggerNN'

# DeepSet:baseline_5param:
#   extends: .ml_pipeline
#   variables:
#     Name: baseline_5param
#     Inputs: baseline
#     DataDir: baselineTRK_5param_221124
#     Dataset: All200.root
#     MINBIAS: MinBias_PU200.root
#     BBBB: ggHHbbbb_PU200.root
#     EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_ntuples_v131Xv9
#     SCRAM_ARCH: 'el9_amd64_gcc12'
#     CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
#     CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3-JetTaggerNN'

# DeepSet:baseline_4param_extended_trk:
#   extends: .ml_pipeline
#   variables:
#     Name: baseline_4param_extended_trk
#     Inputs: baseline
#     DataDir: extendedTRK_4param_221124
#     Dataset: All200.root
#     MINBIAS: MinBias_PU200.root
#     BBBB: ggHHbbbb_PU200.root
#     EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_ntuples_v131Xv9
#     SCRAM_ARCH: 'el9_amd64_gcc12'
#     CMSSW_VERSION: 'CMSSW_14_0_0_pre3'
#     CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_0_0_pre3-JetTaggerNN'

DeepSet:baseline_5param_extended_trk:
  extends: .ml_pipeline
  variables:
    Name: baseline_5param_extended_trk
    Inputs: baseline
    DataDir: extendedTRK_5param_090125
    Dataset: All200.root
    MINBIAS: MinBias_PU200.root
    BBBB: GluGluHHTo4B_PU200.root
    EOS_DATA_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_090125/
    EOS_STORAGE_DIR: /eos/cms/store/cmst3/group/l1tr/MultiJetTagger/
    SCRAM_ARCH: 'el9_amd64_gcc12'
    CMSSW_VERSION: 'CMSSW_14_2_0_pre2'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_2_0_pre2-JetTaggerNN'
