include:
  - local: "CI/template.yml"

DeepSet:all:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: all
    Dataset: jetTuple_TT_PU200.131X_v9a.root

DeepSet:minimal:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: minimal
    Dataset: jetTuple_TT_PU200.131X_v9a.root
