stages:
  - model creation
  - model comparison

model pipelines:
  stage: model creation
  trigger:
    include: CI/child_pipelines.yml
    strategy: depend


test models:
  stage: model comparison
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  script:
    - ./CI/get_artefacts.sh /eos/project/c/cms-l1t-jet-tagger/www/${CI_PROJECT_NAME}/branches/${CI_COMMIT_REF_SLUG}/
  artifacts:
    paths:
      - outputs      
    expire_in: never
