include:
  - local: "CI/template.yml"

DeepSet:baseline_4param:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: baselineTRK_4param_021024
    Dataset: All200_part0.root
    SCRAM_ARCH: 'el8_amd64_gcc11'
    CMSSW_VERSION: 'CMSSW_14_2_0_pre2'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_2_0_pre2'

DeepSet:baseline_5param:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: baselineTRK_5param_021024
    Dataset: All200_part0.root
    SCRAM_ARCH: 'el8_amd64_gcc11'
    CMSSW_VERSION: 'CMSSW_14_2_0_pre2'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_2_0_pre2'

DeepSet:baseline_4param_extended_trk:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: extendedTRK_4param_021024
    Dataset: All200_part0.root
    SCRAM_ARCH: 'el8_amd64_gcc11'
    CMSSW_VERSION: 'CMSSW_14_2_0_pre2'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_2_0_pre2'

DeepSet:baseline_5param_extended_trk:
  extends: .ml_pipeline
  variables:
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: extendedTRK_5param_021024
    Dataset: All200_part0.root
    SCRAM_ARCH: 'el8_amd64_gcc11'
    CMSSW_VERSION: 'CMSSW_14_2_0_pre2'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:P2L1JetTagger_14_2_0_pre2'
