repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace

-   repo: local
    hooks:
    -   id: yaml_config_check
        name: yaml_config_check
        entry: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest #bash -c 'cd tagger/model/configs && python scheme.py'
        language: docker_image
        types: [python]
