name: l1_training
dependencies:
  - python=3.8
  - pip
  - ipykernel
  - pip:
    - numpy
    - matplotlib
    - mplhep
    - tensorflow
    - keras
    - scikit-learn==1.3.2
    - pandas==2.0.3
    - uproot4==4.0.0
    - xxhash