model: DeepSetModelHGQ
run_config :
  verbose : 2
  debug : True

model_config :
  name : baseline_HGQ
  conv1d_layers : [10,10]
  classification_layers : [32,16]
  regression_layers : [10]
  beta: 1.1e-5

quantization_config:
  pt_output_quantization : [16,6]
  
training_config :
  weight_method: "onlyclass"
  epochs : 3
  batch_size : 1024
  learning_rate : 0.001
  validation_split : 0.1

  loss_weights : [1,1]


  EarlyStopping_patience : 10

  ReduceLROnPlateau_factor : 0.5
  ReduceLROnPlateau_patience : 5
  ReduceLROnPlateau_min_lr : 1e-5

hls4ml_config:
  input_precision: 'ap_fixed<24,12,AP_RND,AP_SAT>'
  class_precision: 'ap_ufixed<24,12,AP_RND,AP_SAT>'
  reg_precision: 'ap_fixed<16,6,AP_RND,AP_SAT>'

  project_name: 'L1TSC4NGJetModel_test'
