model: InteractionNetModel
run_config :
  verbose : 2
  debug : True
    
model_config : 
  name : interactionnet
  effects_layers : [16, 16, 16]
  objects_layers : [16]
  classification_layers : [32,16,8]
  regression_layers : [16,8,4]
  kernel_initializer : 'lecun_uniform'
  aggregator : 'mean'

quantization_config:
  quantizer_bits : 9
  quantizer_bits_int : 2
  quantizer_alpha_val : 1
  pt_output_quantization : [16,6]

training_config :
  weight_method: "onlyclass"
  epochs : 10
  batch_size : 1024
  learning_rate : 0.001
  validation_split : 0.1

  loss_weights : [1,1]
  
  initial_sparsity : 0.0
  final_sparsity : 0.1
    
  EarlyStopping_patience : 10

  ReduceLROnPlateau_factor : 0.5
  ReduceLROnPlateau_patience : 5
  ReduceLROnPlateau_min_lr : 1e-5

hls4ml_config:
  input_precision: 'ap_fixed<24,12,AP_RND,AP_SAT>'
  class_precision: 'ap_ufixed<24,12,AP_RND,AP_SAT>'
  reg_precision: 'ap_fixed<16,6,AP_RND,AP_SAT>'
  
  project_name: 'L1TSC4NGJetModel_test'




