include:
    - CI/cmssw.yml
    - template: Code-Quality.gitlab-ci.yml

stages:
  - data
  - train
  - evaluate
  - hls4ml
  - synth
  - emulate
  - emulation-evaluate
  - profile
  - upload
  - test

variables:
    Name: new_samples_baseline_5param_extended_trk
    Inputs: baseline
    Model: baseline
    N_PARAMS: 5
    TRACK_ALGO: extended
    TRAIN: All200.root
    MINBIAS: MinBias_PU200.root
    BBBB: GluGluHHTo4B_PU200.root
    BBBB_EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_090125_addGenH/
    BBTT: GluGluHHTo2B2Tau_PU200.root
    BBTT_EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_090125_addGenH/
    VBFHTAUTAU: VBFHToTauTau_PU200.root
    NTUPLE_TREE: outnano/Jets
    SIGNAL: TT_PU200
    EOS_DATA_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_090125/
    EOS_STORAGE_DIR: /eos/project/c/cms-l1t-jet-tagger/www/${CI_PROJECT_NAME}
    EOS_STORAGE_SUBDIR: branches/${CI_COMMIT_REF_SLUG}/${Name}/pipeline${CI_PIPELINE_ID}
    EOS_STORAGE_DATADIR: branches/${CI_COMMIT_REF_SLUG}/${Name}/TrainingFiles
    CMSSW_VERSION: 'CMSSW_15_1_0_pre1'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:15_1_pre1_L1TSC4NGJetTagger'
    CMSSW_EMULATOR_WRAPPER: 'https://github.com/cms-hls4ml/L1TSC4NGJetModel.git'
    RERUN_ON_TAG: 'False'
    RUN_EMULATION: 'True'
    RUN_SYNTHESIS: 'True'
    TAG: 'v0.0.0'

.template:
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  script:
    - python $FOLDER/$SCRIPT $ARGS
  tags:
    - docker
  # rules: # run automatically on default branch, tags, and on merge requests with 'ci::automatic-build' label; otherwise run manually
  #    - if: '($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_LABELS =~ /ci::automatic-build/)'
  #      when: on_success

data:
  extends:
    - .template
  stage: data
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 32Gi
    KUBERNETES_CPU_REQUEST: 2
  rules:
    - changes:  # Include the job and set to when:manual if any of the follow paths match a modified file.
        - tagger/data/**
      when: manual
  script:
  - source activate tagger
  - mkdir data
  - cd data
  - export EOS_MGM_URL=root://eoscms.cern.ch
  - eos cp $EOS_DATA_DIR/${TRAIN} .
  - eos cp $EOS_DATA_DIR/${SIGNAL}.root .
  - cd ..
  - python tagger/data/make_data.py -i data/${TRAIN} --tree $NTUPLE_TREE -sig $SIGNAL
  - tar -cf training_data_$Inputs.tgz training_data
  - tar -cf signal_process_data.tgz signal_process_data
  - export EOS_MGM_URL=root://eosproject.cern.ch
  - eos mkdir -p ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}
  - eos cp training_data_$Inputs.tgz ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}
  - eos cp signal_process_data.tgz ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}

train:
  extends:
    - .template
  stage: train
  tags: [cern-nextgen-h100]
  needs:
    - job : data
      optional: true
  script:
  - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/training_data_$Inputs.tgz .
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - ./CI/run_training.sh $RERUN_ON_TAG
  artifacts:
    paths:
      - output
      - mlflow_run_id.txt
    exclude:
      - .npy
    expire_in: 1 day

evaluate:
  extends:
    - .template
  stage: evaluate
  tags: [cern-nextgen-h100]
  needs:
    - job : train
      optional: true
  script:
  - nproc
  - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/training_data_$Inputs.tgz .
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - mkdir data
  - cd data
  - eos cp $EOS_DATA_DIR/$MINBIAS .
  - eos cp $BBBB_EOS_DIR/$BBBB .
  - eos cp $BBTT_EOS_DIR/$BBTT .
  - eos cp $EOS_DATA_DIR/$VBFHTAUTAU .
  - eos cp $EOS_DATA_DIR/GluGluHHTo2B2Tau_PU200.root .
  - cd ..
  - echo "VBF tautau performance"
  - python tagger/plot/diTaus.py --deriveWPs --minbias data/$MINBIAS -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus.py --BkgRate --minbias data/$MINBIAS -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus.py --eff --vbf_sample data/$VBFHTAUTAU -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - echo "Topology tautau performance"
  - python tagger/plot/diTaus_topo.py --deriveWPs --minbias data/$MINBIAS -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus_topo.py --BkgRate --minbias data/$MINBIAS -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus_topo.py --eff --vbf_sample data/$VBFHTAUTAU -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - echo "bbbb performance"
  - python tagger/plot/bbbb.py --deriveWPs --minbias data/$MINBIAS -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/bbbb.py --eff -s data/$BBBB -n 500000 --tree $NTUPLE_TREE -m output/$Model
  artifacts:
    paths:
      - output
      - mlflow_run_id.txt
    when: always
    exclude:
      - .npy
    expire_in: 7 days

hls4ml:
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 32Gi
    KUBERNETES_CPU_REQUEST: 4
  extends:
    - .template
  rules:
    - if: $RUN_SYNTHESIS == "True"
  stage: hls4ml
  needs:
    - job : train
      optional: true
  script:
  - source activate tagger
  - python tagger/firmware/hls4ml_convert.py -m output/$Model -o firmware
  artifacts:
    paths:
      - output/$Model/firmware
    expire_in: 1 day

synth:
  tags:
    - fpga-large
  image: registry.cern.ch/ci4fpga/vivado:2023.2
  stage: synth
  needs : [hls4ml]
  rules:
    - if: $RUN_SYNTHESIS == "True"
  script:
    - cd output/$Model/firmware/L1TSC4NGJetModel_test
    - vitis_hls -f build_prj.tcl
    - vivado -mode batch -source vivado_synth.tcl
    - cd ../../..
  artifacts:
    paths:
      - output/$Model/firmware/L1TSC4NGJetModel_test
    expire_in: 1 day

emulation-evaluate:
  extends:
    - .template
  stage: emulation-evaluate
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 8Gi
    KUBERNETES_CPU_REQUEST: 2
  rules:
    - if: ($RUN_EMULATION == "True") && ($RUN_SYNTHESIS == "True")
  needs: [emulate,train,hls4ml]
  dependencies: [emulate,train,hls4ml]
  script:
  - mkdir data
  - cd data
  - cp ../${CMSSW_VERSION}/src/FastPUPPI/NtupleProducer/python/jetTuple_${TRACK_ALGO}_${N_PARAMS}.root .
  - cd ..
  - source activate tagger
  - python tagger/plot/makeEmulationPlot.py -r True -i data/jetTuple_${TRACK_ALGO}_${N_PARAMS}.root -m output/$Model
  artifacts:
    paths:
      - output/baseline
    expire_in: 1 day

profile:
  extends:
    - .template
  stage: profile
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 8Gi
    KUBERNETES_CPU_REQUEST: 2
  needs: [emulate,synth,train]
  dependencies: [emulate,synth,train]
  rules:
    - if: ($RUN_EMULATION == "True") &&  ($RUN_SYNTHESIS == "True")
  script:
  - source activate tagger
  - mkdir data
  - cd data
  - cp ../${CMSSW_VERSION}/src/FastPUPPI/NtupleProducer/python/jetTuple_${TRACK_ALGO}_${N_PARAMS}.root .
  - cd ..
  - pip uninstall hls4ml -y
  - git clone https://github.com/CMS-L1T-Jet-Tagging/hls4ml.git -b jet_tagger
  - cd hls4ml
  - pip install .[profiling]
  - cd ..
  - python tagger/firmware/hls4ml_profile.py -r True -i data/jetTuple_${TRACK_ALGO}_${N_PARAMS}.root -m output/$Model
  artifacts:
    paths:
      - output/baseline
    expire_in: 1 day

upload_new_model:
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest
  stage: upload
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_CPU_REQUEST: 1
  needs: [train,evaluate]
  needs: 
    - job: emulation-evaluate
      optional: true
  needs: 
    - job: hls4ml
      optional: true
  needs: 
    - job: profile
      optional: true
  rules:
    - if: $RERUN_ON_TAG == "False"
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  script:
    - ./CI/upload_new_model.sh
  artifacts:
    paths:
      - $Name
    expire_in: 1 day


upload_tagged_model:
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest
  stage: upload
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_CPU_REQUEST: 1
  needs: [emulation-evaluate,hls4ml,train,evaluate,profile]
  dependencies: [emulation-evaluate,hls4ml,train,evaluate,profile]
  rules:
    - if: $RERUN_ON_TAG == "True"
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  script:
    - source activate tagger
    - mkdir -p ${EOS_STORAGE_DIR}/tags/${TAG}/test/firmware
    - mkdir -p ${EOS_STORAGE_DIR}/tags/${TAG}/test/plots
    - mkdir $Name
    - cd tagger/firmware
    - tar -cvf L1TSC4NGJetModel.tgz L1TSC4NGJetModel
    - cp -r L1TSC4NGJetModel.tgz ${EOS_STORAGE_DIR}/tags/${TAG}/test/firmware/
    - cd ../..
    - mkdir $Name/plots
    - mv output/baseline/plots/emulation $Name/plots
    - mv output/baseline/plots/profile $Name/plots
    - mv output/baseline/plots/training/ $Name/plots
    - mv output/baseline/plots/physics/ $Name/plots
    - cd ..
    - rm -rf php-plots
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch/cms-analysis/general/php-plots.git -b feature/update_extension_grouping
    - export PATH="${PATH}:/builds/ml_l1/php-plots/bin"
    - pb_copy_index.py TrainTagger/${Name} --recursive
    - pb_copy_index.py ${EOS_STORAGE_DIR}/tags/${TAG}/test --recursive
    - cd TrainTagger/${Name}
    - pb_deploy_plots.py plots ${EOS_STORAGE_DIR}/tags/${TAG}/test/plots --recursive --extensions png,pdf
  artifacts:
    paths:
      - $Name
    expire_in: 1 day

code_quality:
   tags:
    - docker-privileged-xl
   artifacts:
    paths: [gl-code-quality-report.json]
