include:
    - CI/cmssw.yml
    - project: cms-cactus/ops/auto-devops
      ref: 0.4.1
      file: templates/upload-eos.yml


stages:
  - data
  - train
  - evaluate
  - synth
  - emulate
  - emulation-evaluate
  - pre-upload
  - upload
   
variables:
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: ./
    Dataset: All200.root

.template:
  image: gitlab-registry.cern.ch/cebrown/docker-images/mamba_jettagger:latest
  before_script:
    - export PYTHONPATH=/builds/cebrown/TrainTagger:$PYTHONPATH
    - mc alias set $ARTIFACTS_ALIAS http://$ARTIFACTS_HOST $ARTIFACTS_ACCESS_KEY $ARTIFACTS_SECRET_KEY
    - mc admin info $ARTIFACTS_ALIAS
  script:
    - python $FOLDER/$SCRIPT $ARGS
  tags:
    - docker
  # rules: # run automatically on default branch, tags, and on merge requests with 'ci::automatic-build' label; otherwise run manually
  #    - if: '($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_LABELS =~ /ci::automatic-build/)'
  #      when: on_success

data:
  extends:
    - .template
  stage: data
  rules:
     - changes:  # Include the job and set to when:manual if any of the follow paths match a modified file.
         - datatools/**
  when: manual
  script:
  - ls /opt/Xilinx
  - source activate l1_training
  - mkdir data
  - cd data
  - echo $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/$Dataset 
  - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/$Dataset ./
  - cd ..
  - python datatools/createDataset.py -i data/$Dataset -o data/All -t $Inputs
  - cd data 
  - tar -cvf convertedfiles_$Inputs.tgz All
  - mc cp convertedfiles_$Inputs.tgz $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir
train:
  extends:
    - .template
  stage: train
  needs: 
    - job : data
      optional: true
  script:
  - mkdir data
  - cd data
  - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/convertedfiles_$Inputs.tgz ./
  - tar -xvf convertedfiles_$Inputs.tgz
  - cd ..
  - source activate l1_training
  - python train/training.py -t data/All -c $Classes -i $Inputs --train-epochs 15 --model $Model --classweights --regression --learning-rate 0.001 --nNodes 16 --optimizer adam --train-batch-size 2048 --strstamp 2024_10_10_vTEST --nLayers 2 --pruning
  artifacts:
    paths:
      - trainings_regression_weighted
    expire_in: 1 day

evaluate:
  extends:
    - .template
  stage: evaluate
  needs: [train]
  dependencies: [train]
  script:
  - mkdir data
  - cd data
  - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/convertedfiles_$Inputs.tgz ./
  - tar -xvf convertedfiles_$Inputs.tgz
  - cd ..
  - ls -lh
  - ls trainings_regression_weighted
  - source activate l1_training
  - python evaluation/makeResultPlot.py -t data/All -f trainings_regression_weighted -c $Classes -i $Inputs --model $Model -o with_regression --regression --timestamp 2024_10_10_vTEST --pruning
  - python evaluation/makeInputPlots.py -t data/All -f trainings_regression_weighted -c $Classes -i $Inputs
  artifacts:
    paths:
      - trainings_regression_weighted
      - outputPlots
      - inputFeaturePlots
    expire_in: 1 day

synth:
  extends:
    - .template
  stage: synth
  tags:
    - cb_vivado
  needs : [train]
  dependencies : [train]
  script:
    - source /opt/Xilinx/Vivado/2022.2/settings64.sh
    - export PATH="/externalopt/modelsim/2019.2/modeltech/bin/:$PATH"
    - export LD_LIBRARY_PATH=/externalopt/cactus/lib:$LD_LIBRARY_PATH
    - export PYTHONPATH=/builds/cebrown/TrainTagger:$PYTHONPATH
    - mkdir data
    - cd data
    - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/convertedfiles_$Inputs.tgz ./
    - tar -xvf convertedfiles_$Inputs.tgz
    - cd ..
    - source activate l1_training
    - python synthesis/synth.py -f data/All -c $Classes -i $Inputs -m $Model -o regression --regression --timestamp 2024_10_10_vTEST -B --pruning
  artifacts:
    paths:
      - outputSynthesis/*
    expire_in: 1 day


emulation-evaluate:
  extends:
    - .template
  stage: emulation-evaluate
  tags:
    - cb_vivado
  needs: [emulate,train,synth]
  dependencies: [emulate,train,synth]
  tags:
    - cb_vivado
  script:
  - mkdir data
  - cd data
  - cp ../${CMSSW_VERSION}/src/FastPUPPI/NtupleProducer/python/jetTuple.root .
  - cd ..
  - source activate l1_training
  - python datatools/createDataset.py -i data/jetTuple.root -o data/Emu -t $Inputs
  - cp synthesis/* evaluation
  - python evaluation/makeEmulationPlot.py -t data/Emu -f trainings_regression_weighted -c $Classes -i $Inputs --model $Model -o with_regression --regression --timestamp 2024_10_10_vTEST --pruning
  artifacts:
    paths:
      - emulationPlots
    expire_in: 1 day

pre-upload:
  extends:
    - .template
  stage: pre-upload
  tags:
    - cb_vivado
  needs: [emulation-evaluate,synth,train,evaluate]
  dependencies: [emulation-evaluate,synth,train,evaluate]
  tags:
    - cb_vivado
  script:
    - cd ..
    - git clone https://gitlab.cern.ch/cms-analysis/general/php-plots.git
    - pwd
    - export PATH="${PATH}:/builds/cebrown/php-plots/bin"
    - pb_copy_index.py TrainTagger/ --recursive
    - pb_pdf_to_png.py TrainTagger/ --recursive
    - cd TrainTagger
  artifacts:
    paths:
      - emulationPlots
      - outputSynthesis
      - trainings_regression_weighted
      - outputPlots
      - inputFeaturePlots
    expire_in: 1 day

upload:
  extends: .auto_devops_upload_eos_template
  image: gitlab-registry.cern.ch/cms-cactus/ops/auto-devops/eos:tag-0.4.1
  stage: upload
  tags: [ k8s-eos ]
  needs: [pre-upload]
  dependencies: [pre-upload]
  before_script:
    - yum install -q -y git
  variables:
    CERNBOX_FOLDER: /eos/user/c/cebrown/www/JetTagging/${CI_PROJECT_NAME}/${CI_JOB_NAME}
  script:
    - |
      export EOS_MGM_URL=eosuser.cern.ch
      echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
      eos cp -r emulationPlots/ $CERNBOX_FOLDER
      eos cp -r outputSynthesis/ $CERNBOX_FOLDER
      eos cp -r trainings_regression_weighted/ $CERNBOX_FOLDER
      eos cp -r outputPlots/ $CERNBOX_FOLDER
      eos cp -r inputFeaturePlots/ $CERNBOX_FOLDER
