include:
    - CI/cmssw.yml

stages:
  - data
  - train
  - evaluate
  - synth
  - emulate
  - emulation-evaluate
  - profile
  - upload

variables:
    Name:  baseline_4_params
    Model: DeepSet
    Classes: btgc
    Inputs: baseline
    DataDir: ./
    Dataset: All200.root

.template:
  image: gitlab-registry.cern.ch/cebrown/docker-images/mamba_jettagger:latest
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null 
    - mc alias set $ARTIFACTS_ALIAS http://$ARTIFACTS_HOST $ARTIFACTS_ACCESS_KEY $ARTIFACTS_SECRET_KEY
    - mc admin info $ARTIFACTS_ALIAS
  script:
    - python $FOLDER/$SCRIPT $ARGS
  tags:
    - docker
  # rules: # run automatically on default branch, tags, and on merge requests with 'ci::automatic-build' label; otherwise run manually
  #    - if: '($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_LABELS =~ /ci::automatic-build/)'
  #      when: on_success

data:
  extends:
    - .template
  stage: data
  image: gitlab-registry.cern.ch/cebrown/docker-images/mamba_jettagger:latest
  # rules:
  #    - changes:  # Include the job and set to when:manual if any of the follow paths match a modified file.
  #        - tagger/data/**
  # when: manual
  script:
  - source activate tagger
  - mkdir data
  - cd data
  - eos cp /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_090125/All200.root .
  - cd ..
  - python tagger/train/train.py --make-data -i data/All200.root
  - tar -cf training_data_$Inputs.tgz training_data
  - mc cp training_data_$Inputs.tgz $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir

train:
  extends:
    - .template
  stage: train
  needs: 
    - job : data
      optional: true
  script:
  - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/training_data_$Inputs.tgz ./
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - python tagger/train/train.py -n $Name -p 50
  - python tagger/train/train.py --plot-basic -n $Name
  - cd output/baseline
  - tar -cf testing_data_$Inputs.tgz testing_data
  - mc cp testing_data_$Inputs.tgz $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir
  artifacts:
    paths:
      - output
      - mlflow_run_id.txt
    exclude:
      - .npy
    expire_in: 1 day

evaluate:
  extends:
    - .template
  stage: evaluate
  image: gitlab-registry.cern.ch/cebrown/docker-images/mamba_jettagger:latest
  needs: [train]
  dependencies: [train]
  script:
  - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/training_data_$Inputs.tgz ./
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  - mkdir data
  - cd data
  - eos cp $EOS_DIR/$MINBIAS .
  - eos cp $EOS_DIR/$BBBB .
  - cd ..
  - python tagger/plot/bbbb.py --deriveWPs --minbias data/$MINBIAS -n 650000
  - python tagger/plot/bbbb.py --eff -s data/$BBBB -n 500000
  - cd output/baseline
  - mc cp $ARTIFACTS_ALIAS/$ARTIFACTS_BUCKET/$DataDir/testing_data_$Inputs.tgz ./
  - tar -xf testing_data_$Inputs.tgz
  - cd ../..
  artifacts:
    paths:
      - output
      - mlflow_run_id.txt
    exclude:
      - .npy
    expire_in: 1 day

synth:
  extends:
    - .template
  stage: synth
  tags:
    - cb_vivado
  needs : [train]
  dependencies : [train]
  script:
    - source /opt/Xilinx/Vivado/2024.1/settings64.sh
    - export PATH="/externalopt/modelsim/2019.2/modeltech/bin/:$PATH"
    - export LD_LIBRARY_PATH=/externalopt/cactus/lib:$LD_LIBRARY_PATH
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - source activate tagger
    - python tagger/firmware/hls4ml_convert.py -n $Name
  artifacts:
    paths:
      - tagger/firmware
      - mlflow_run_id.txt
    expire_in: 1 day

emulation-evaluate:
  extends:
    - .template
  stage: emulation-evaluate
  tags:
    - cb_vivado
  needs: [emulate,train,synth]
  dependencies: [emulate,train,synth]
  script:
  - mkdir data
  - cd data
  - cp ../${CMSSW_VERSION}/src/FastPUPPI/NtupleProducer/python/jetTuple_extended_5.root .
  - cd ..
  - source activate tagger
  - python tagger/plot/makeEmulationPlot.py -r True
  artifacts:
    paths:
      - output/baseline
    expire_in: 1 day

profile:
  extends:
    - .template
  stage: profile
  tags:
    - cb_vivado
  needs: [emulate,train,synth]
  dependencies: [emulate,train,synth]
  script:
  - source /opt/Xilinx/Vivado/2024.1/settings64.sh
  - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
  - source activate tagger
  - mkdir data
  - cd data
  - cp ../${CMSSW_VERSION}/src/FastPUPPI/NtupleProducer/python/jetTuple_extended_5.root .
  - cd ..
  - pip uninstall hls4ml -y
  - git clone https://github.com/CMS-L1T-Jet-Tagging/hls4ml.git -b jet_tagger
  - cd hls4ml
  - pip install .[profiling]
  - cd ..
  - python tagger/firmware/hls4ml_profile.py -r True
  artifacts:
    paths:
      - output/baseline
    expire_in: 1 day

upload:
  tags: [k8s-gpu]
  image: gitlab-registry.cern.ch/cebrown/docker-images/mamba_jettagger:latest
  stage: upload
  needs: [emulation-evaluate,synth,train,evaluate,profile]
  dependencies: [emulation-evaluate,synth,train,evaluate,profile]
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
  script:
    - mkdir $Name
    - mv tagger/firmware $Name
    - mkdir $Name/plots
    - mv output/baseline/model $Name/model
    - mv output/baseline/plots/emulation $Name/plots
    - mv output/baseline/plots/profile $Name/plots
    - mv output/baseline/plots/training/ $Name/plots
    - mv output/baseline/plots/physics/ $Name/plots
    - cd ..
    - rm -rf php-plots
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch/cms-analysis/general/php-plots.git -b feature/update_extension_grouping
    - export PATH="${PATH}:/builds/ml_l1/php-plots/bin"
    - pb_copy_index.py TrainTagger/${Name} --recursive
    - pb_deploy_plots.py TrainTagger/${Name} /eos/user/c/cebrown/www/JetTagging/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME} --recursive --extensions h5,cpp,h,yml,tcl,sh,png,pdf,rpt 
  artifacts:
    paths:
      - $Name
    expire_in: 1 day
